// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRqvKopigdBCF14AvGF_g5qpPEEr1XZow',
    appId: '1:926878754392:web:b92317b6a2025fc98e8c2d',
    messagingSenderId: '926878754392',
    projectId: 'job-connect-822d3',
    authDomain: 'job-connect-822d3.firebaseapp.com',
    storageBucket: 'job-connect-822d3.appspot.com',
    measurementId: 'G-TT0LNTH9M2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD1PAmnOAlhfg0SjNqbOBmpBv6Dzecnig',
    appId: '1:926878754392:android:9c08199c0bf69f828e8c2d',
    messagingSenderId: '926878754392',
    projectId: 'job-connect-822d3',
    storageBucket: 'job-connect-822d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACrDYwmCYLCVOHpJCUtDnoyDpYxdzJ2bY',
    appId: '1:926878754392:ios:a3528ddba943603c8e8c2d',
    messagingSenderId: '926878754392',
    projectId: 'job-connect-822d3',
    storageBucket: 'job-connect-822d3.appspot.com',
    androidClientId: '926878754392-p7brm3qmda5uk6e8aa8p58791ujjjbok.apps.googleusercontent.com',
    iosClientId: '926878754392-clg4t7j1534dl113lbbovt6oli0k3g91.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobPortel',
  );

}